### ISSUE TITLE
🧹 Chore: Add repo scaffolding

### ISSUE THREAD

**Issue by e-lo** [BayAreaMetro/tm2py#1]
As a developer, I'd like to have a basic set of infrastructure set up in this github repo to enable efficient and high-quality software development.

### Outcomes

- [x] `setup.py` 
- [x] `.gitignore` 
- [x] folder structure 
- [x] precommit hooks 
- [x] PR templates 
- [x] issue templates 
- [x] README 
- [ ] branch restrictions 
- [x] `development_requirements.txt` 

### Relevant Background

- [Requirements Document description ](https://docs.google.com/document/d/1Zx3aKg4olK_w9DqpjaRUJcfb_R78tozGyTtR-XDy9OY/edit#heading=h.1red7scaff1) (closed doc't)

**Comment by e-lo** [comment]
@lmz  to add who should be on the main branch approved reviewer list.  Will start with two reviewers to go to `main`.

**Comment by e-lo** [comment]
cc: @lmz in case she has any more thoughts on this, otherwise will finish/close

**Comment by lmz** [comment]
Will take a look at this; some references: 

- Protected Branches: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches
- Code Owners: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

**Comment by e-lo** [comment]
pinging @lmz again to see if she wants to branch restrictions in this development cycle or if I should set up a separate issue to track this and leave in background for now?
