### ISSUE TITLE
🚀 Feature: Refine subset of links for highway assignment network

### ISSUE THREAD

**Issue by i-am-sijia** [BayAreaMetro/tm2py#115]
### User Story
Issues: 

What link subset should be used for the highway network? Discussed in the [June 14, 2023 meeting](https://app.asana.com/0/1199982433633229/1204767620105873/f) with MTC.

Currently using "assignable" links (`assignable = 1`). `assignable` was the old approach used and inherited from TM2.0. But it includes e.g. service roads, which has `FT = 99`. The Facility Type definition can be found in the [network PRD](https://docs.google.com/document/d/17OeXT8jxIst-vmGLl6eZVXx5b20cmct1p1WOpAuhi0M/edit).
The issue occurs when the FT 99 links do not have meaningful capacity in the assignment, which is defined in the [model_config.toml](https://github.com/BayAreaMetro/tm2py/blob/c0f9467e47cfff1bb2fb4c49113dea1751fb6ff0/examples/model_config.toml#L1379-L1413). They will have infinite travel time in the assignment. And the infinite travel time will be inherited by transit assignment and skimming.

Solutions:

1. Temporarily added capacities for FT 99 so that they will have meaningful travel time in the assignment
2. Another option to consider: Link 21 used `FT <= 8` for highway assignment network, instead of assignable. It includes everything except service roads. If we use Link 21 option, there will be more links in the highway network, which increases run time. We should probably do another round of roadway trimming. And we will also need to rebuild centroid connectors

Progress:

- [x] Sufficiently defined
- [ ] Approach determined
- [ ] Tests developed
- [ ] User story satisfied
- [ ] Doc strings
- [ ] General documentation
- [ ] Passing tests

### Who should be involved?
Users: 
Reviewers: 

#### Tests

- [ ] Test for...

**Comment by DavidOry** [comment]
Replaced by #147
