### ISSUE TITLE
🧹 Chore: Grant Arash Write Access

### ISSUE THREAD

**Issue by DavidOry** [BayAreaMetro/tm2py#121]
Please give @arashasadabadi write access the the repository.

**Comment by lmz** [comment]
Looks like this was already done: 
<img width="1382" alt="image" src="https://github.com/BayAreaMetro/tm2py/assets/796272/a89e459d-0d67-4e61-b22b-54b66014b6f6">

**Comment by DavidOry** [comment]
fyi @arashasadabadi 
thanks @lmz!
