### ISSUE TITLE
[Refactor] Create overall code structure

### ISSUE THREAD

**Issue by e-lo** [BayAreaMetro/tm2py#15]
*As a developer, I'd like to have an overall structure of code to work with and 'fill in' as we add functionality and features*

Structure should include:
- [x] highway 
- [x] controller 
- [x] component
- [x] active modes
- [x] visitor
- [x] truck
- [x] tests
- [x] logging
- [x] documentation
- [x] parameters

Reviewers: @inrokevin @lmz @davidory

**Comment by e-lo** [comment]
@inrokevin I think this is all taken care of in #16 but for visitors?  Can you create a stub for that and then check this off?

**Comment by inrokevin** [comment]
Placeholder script added

**Comment by e-lo** [comment]
As a matter of housekeeping, let's keep this open until is is merged in to one of the two main branches via a PR merge.  

Checking it off here and moving it to ["ready" in the project](https://github.com/BayAreaMetro/tm2py/projects/1#card-79107798) indicate your part is done pending a review. 

Should all of this be assigned to the "architecture" branch and PR or other?

**Comment by e-lo** [comment]
Closed via #16
