### ISSUE TITLE
🚀 Feature: Test OpenPaths EMME 2024's Ignore Cosmetic Nodes Feature in Highway Assignment

### ISSUE THREAD

**Issue by i-am-sijia** [BayAreaMetro/tm2py#151]
### User Story
The existing TM2 roadway network is highly detailed, including every street, bicycle path, and sidewalk. When the roadway network is extracted from this network, it contains numerous nodes that are unnecessary for roadway assignment.

OpenPaths EMME 2024 allows ignoring the cosmetic nodes in the highway assignment to speed up run time. We will test it to confirm the details.

Progress:

- [x] Sufficiently defined
- [x] Approach determined
- [x] Tests developed
- [ ] User story satisfied
- [x] Doc strings
- [ ] General documentation
- [x] Passing tests

### Priority 
High

### Level of Effort
Low

### Resolution Ideas
With the new EMME, we should be able to add an assignment argument to trigger the ignoring of cosmetic nodes.

### Project
Task Order 5

### Who should be involved?
Users: @gregerhardt, @FlaviaTsang, @lmz
Reviewers: @i-am-sijia, @DavidOry

### Risk
We need to confirm if the output assigned network is in the original format with the cosmetic nodes, or in a simplified format that does not have the cosmetic nodes. It sounds like it should be the former.(?)

#### Tests

- [ ] Test for...

**Comment by i-am-sijia** [comment]
OpenPaths testing plan:

- [ ] Step 1: Test run 11 assignment with OpenPaths. This will tell us if switching to OpenPaths alone will save run time.
- [ ] Step 2: Check the network accelerate box – this is a new algorithm in OpenPaths, not related to excessive nodes. Compared to Step 1, this will tell us if the network accelerate alone saves  run time. 
- [ ] Step 3: network accelerate & remove excessive nodes. “Remove cosmetic nodes” this will create an irreversible network. If the result of Steps 1 & 2 are not desirable, we will test Step 3. If Step 3 result is desirable, we will remove cosmetic nodes in Lasso when writing out Emme network, so that we have correspondence between the standard network and the network after node removal.

**Comment by lachlan-git** [comment]
Step 1,2 and 3 have been tested on embank with FT classes 1-7 included:

| Desciption                                                                           | VDI Machine           | number of iterations [EA, AM, MD, PM, EV] | time for for highway assignment and skims |
| ------------------------------------------------------------------------------------ | --------------------- | ----------------------------------------- | ----------------------------------------- |
| Base case<br>FT  7 included included<br>Network Accelerate = False                   | Lachlan Tier 2 Pool B | [3, 13, 10, 30, 4]                        | 6 hours and 15 minutes                    |
| same as base Case except:<br> network accelerate = True                              | Lachlan Tier 2 pool B | [3, 12, 10, 24, 4]                        | 4 hours and 15 minutes                    |
| same as base Case except:<br>network accelerate = True<br>Emme remove_cosmetic_nodes | Lachlan Tier 2 pool A | [3, 12, 9, 23, 4]                         | 3 hours and 30 minutes                    |

**Comment by lachlan-git** [comment]
|    | bases               | comparisons         |   func_types |   slopes |   r_vals |
|---:|:--------------------|:--------------------|-------------:|---------:|---------:|
|  0 | @volau_run23_scenAM | @volau_run15_scenAM |            1 |  1.01876 | 0.999232 |
|  1 | @volau_run23_scenAM | @volau_run15_scenAM |            2 |  1.01646 | 0.998094 |
|  2 | @volau_run23_scenAM | @volau_run15_scenAM |            3 |  1.00419 | 0.991191 |
|  3 | @volau_run23_scenAM | @volau_run15_scenAM |            4 |  1.00159 | 0.98945  |
|  4 | @volau_run23_scenAM | @volau_run15_scenAM |            5 |  1.00303 | 0.987782 |
|  5 | @volau_run23_scenAM | @volau_run15_scenAM |            6 |  0.99131 | 0.979935 |
|  6 | @volau_run23_scenAM | @volau_run24_scenAM |            1 |  1.01876 | 0.999232 |
|  7 | @volau_run23_scenAM | @volau_run24_scenAM |            2 |  1.01646 | 0.998094 |
|  8 | @volau_run23_scenAM | @volau_run24_scenAM |            3 |  1.00419 | 0.991191 |
|  9 | @volau_run23_scenAM | @volau_run24_scenAM |            4 |  1.00159 | 0.98945  |
| 10 | @volau_run23_scenAM | @volau_run24_scenAM |            5 |  1.00303 | 0.987782 |
| 11 | @volau_run23_scenAM | @volau_run24_scenAM |            6 |  0.99131 | 0.979935 |
| 12 | @volau_run23_scenAM | @volau_run25_scenAM |            1 |  1.01876 | 0.999232 |
| 13 | @volau_run23_scenAM | @volau_run25_scenAM |            2 |  1.01646 | 0.998094 |
| 14 | @volau_run23_scenAM | @volau_run25_scenAM |            3 |  1.00419 | 0.991191 |
| 15 | @volau_run23_scenAM | @volau_run25_scenAM |            4 |  1.00159 | 0.98945  |
| 16 | @volau_run23_scenAM | @volau_run25_scenAM |            5 |  1.00303 | 0.987782 |
| 17 | @volau_run23_scenAM | @volau_run25_scenAM |            6 |  0.99131 | 0.979935 |

**Comment by DavidOry** [comment]
@lachlan-git: can you please edit the above table to:

1. Replace the "runXX" code with a more meaningful description.
2. Replace the "func_types" code with the word labels.
3. Use two decimals for the quantities. 

thanks.

**Comment by lachlan-git** [comment]
done
