### ISSUE TITLE
🚀 Feature: Use Warm Start Skims or Warm Start Demand

### ISSUE THREAD

**Issue by DavidOry** [BayAreaMetro/tm2py#155]
### User Story
The current warm start procedures conduct a roadway and transit assignment. This is desirable, as a new roadway network or transit service can result in different skims. However, the roadway and transit assignment runtimes are lengthy. When modest changes to the roadway or transit networks are present, a set of warm start skims may be sufficient to get the model to an equilibrium across the expected three global iterations. It would therefore be nice to have the option to do a warm start assignment or use warm start skims and skip the assignment.  

Progress:

- [x] Sufficiently defined
- [x] Approach determined
- [x] Tests developed
- [x] User story satisfied
- [ ] Doc strings
- [ ] General documentation
- [ ] Passing tests

### Priority 
Medium

### Level of Effort
Low

### Resolution Ideas
Modify the implementation procedures to allow a user to skip the warm start assignment and skimming steps and use warm start skims directly. Users should continue to be able to do warm start assignments, but not be forced to. 

### Project
Task Order 5

### Who should be involved?
Users: @gregerhardt, @lmz, @FlaviaTsang 
Reviewers: @DavidOry 

### Risk
Low as we are, in effect, just skipping a few steps. 

#### Tests
No unit tests are needed. We do need: 

- [ ] Test warm start and one iteration with skims option
- [ ] Test warm start and one iteration with assignment option

**Comment by i-am-sijia** [comment]
Pseudo logic:

1. If not `warmstart`
    - run highway, transit assignment and skimming in iteration 0, with **zero** demand
2. If `warmstart`
    - assert `use_warmstart_skim` XOR `use_warmstart_demand`
    - if `use_warmstart_skim`
        - skip highway, transit assignment and skimming in iteration 0
    - if `use_warmstart_demand`
        - run highway, transit assignment and skimming in iteration 0, with non-zero demand
