### ISSUE TITLE
[Feat] Emme common code

### ISSUE THREAD

**Issue by inrokevin** [BayAreaMetro/tm2py#23]
*As a user, I'd like to have a set of tm2py components which interact with Emme APIs* 

This issue is complete when there are components for:

- [x] `EmmeManager`: central tool to wrap accessing essential Emme interfaces
- [x] `MatrixCache`: simple write-through cache (to Emmebank) of matrix data as Numpy arrays, to support in-memory calculations of skim results (e.g. set intra-zonal values) and subsequent export to OMX 
- [x] `OMXManager`: Wrapper for the OMX interface to write from Emme matrices and numpy arrays to OMX files, interact with MatrixCache and read from OMX to demand data.
- [x] `NetworkCalculator`: Simple wrapper for Emme network calculator to generate specs and call the Network calculation Modeller tool.

**Comment by e-lo** [comment]
@inrokevin I think this is all "ready" in the branch - if so can you check off the above so it appears as such :-)

**Comment by e-lo** [comment]
Closed via #16
