### ISSUE TITLE
🚀 Feature: Add Emme Mock Fixture

### ISSUE THREAD

**Issue by e-lo** [BayAreaMetro/tm2py#24]
### User Story
*As a user who doesn't have Emme and/or developer who wants to have continuous integration tests run on Github Actions, I'd like to have a useful substitute or mock for Emme.*

### Priority 
Medium - but important because allows more continuous integration testing

### Level of Effort
Medium

### Resolution Ideas
Use the Python [MagicMock](https://realpython.com/python-mock-library/) module and create a mocked inro module fixture that can be imported into anything that might need it, including:

- [ ] Tests run on platforms without Emme license
- [ ] Documentation building

### Project
*Is there a funder or project associated with this feature?*

### Who should be involved?
Commenters:  
Users: Github Actions
Reviewers: @e-lo 

### Risk
*Will this potentially break anything?*

This should make things more useful.

#### Tests
*What are relevant tests or what tests need to be created in order to determine that this issue is complete?*

One that tests using the Emme Manager without an Emme license

**Comment by lmz** [comment]
Another thing that's related to the Emme install:
It looks like Emme comes with and installs `Pygments-2.3.1` because it's required by `ipython` which is required by `inro-modeller`:

```
(tm2py) Z:\example_union_test_highway>pip show pygments
Name: Pygments
Version: 2.3.1
Summary: Pygments is a syntax highlighting package written in Python.
Home-page: http://pygments.org/
Author: Georg Brandl
Author-email: georg@python.org
License: BSD License
Location: c:\program files\inro\emme\emme 4\emme-4.6.0\python37\lib\site-packages
Requires:
Required-by: ipython, jupyter-console, nbconvert, qtconsole, Sphinx

(tm2py) Z:\example_union_test_highway>pip show ipython
Name: ipython
Version: 7.9.0
Summary: IPython: Productive Interactive Computing
Home-page: https://ipython.org
Author: The IPython Development Team
Author-email: ipython-dev@python.org
License: BSD
Location: c:\program files\inro\emme\emme 4\emme-4.6.0\python37\lib\site-packages
Requires: backcall, colorama, decorator, jedi, pickleshare, prompt-toolkit, pygments, setuptools, tr
aitlets
Required-by: inro-dynameq, inro-modeller, ipykernel, ipywidgets, jupyter-console
```

This is preventing me from installing the mkdocs-related packages which wants a more recent version of pygments:
```
(tm2py) Z:\example_union_test_highway>pip install mkdocs mkdocs-autorefs mkdocs-awesome-pages-plugin mkdocs-material mkdocs-material-extensions mkdocstrings
Requirement already satisfied: mkdocs in c:\users\mtcpb\.conda\envs\tm2py\lib\site-packages (1.2.3)
Collecting mkdocs-autorefs
  Downloading mkdocs_autorefs-0.4.1-py3-none-any.whl (9.8 kB)
[...]
Collecting pygments>=2.10
  Using cached Pygments-2.11.2-py3-none-any.whl (1.1 MB)
[...]
Installing collected packages: cached-property, pygments, mkdocs-material-extensions, bracex, astunparse, wcmatch, pytkdocs, mkdocs-material, mkdocs-awesome-pages-plugin, mkdocs-autorefs, mkdocstrings
-python-legacy, mkdocstrings
  Attempting uninstall: pygments
    Found existing installation: Pygments 2.3.1
    Uninstalling Pygments-2.3.1:
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'c:\\program files\\inro\\emme\\emme 4\\emme-4.6.0\\python37\\lib\\site-packages\\pygments-2.3.1.dist-info\\DESCRIPTION.rst'
Consider using the `--user` option or check the permissions.
```

**Comment by e-lo** [comment]
[ adding above as issue #26 ]
