### ISSUE TITLE
🧹 Chore: Address github page serving settings

### ISSUE THREAD

**Issue by e-lo** [BayAreaMetro/tm2py#76]
Github pages isn't serving our mike-generated mkdocs documentation :-(

@lmz (or somebody with repo management privileges) is best-poised to investigate. 

Progress:

- [x] Sufficiently defined
- [x] Approach decided
- [x] Implemented

**Comment by lmz** [comment]
I think this is working now: https://bayareametro.github.io/tm2py/develop/
Sorry for delays!
