### ISSUE TITLE
🧹 Chore: Customize pre-commit check - remove black

### ISSUE THREAD

**Issue by lmz** [BayAreaMetro/tm2py#91]
I'd like to loosen up the black portion of the pre-commit check
Because I like the readability of certain spacing
See the rejections here:
https://github.com/BayAreaMetro/tm2py/actions/runs/3301511689/jobs/5447061855

Progress:

- [ ] Sufficiently defined
- [ ] Approach decided
- [ ] Implemented

**Comment by lmz** [comment]
It's possible that black is too pushy for my taste:

Per https://github.com/psf/black/issues/1480; Last comment: 
> For people who end up here: if you need to use Black to enforce automated code formatting then you need to have totally standardized code format. "Black" comes from "Black and White", so there is no debate, no configuration, no optionality. This is good if you have Python developers who don't know how to naturally write good, readable, consistent code -- and under these circumstances you should definitely use black. In any other situation the issue of code readability is so important that I would suggest you should never consider using Black and instead make sure your team of experienced/professional software engineers understand the importance of readability and comment, document, organize the code in smart & readable ways. Black won't solve the problem of bad semantics, bad code organization, bad commenting, bad style. For all those you need coding standards and code reviews. Configurable linters are nice to pick up warnings and to check that some testable features of coding standards are adhered to, or at least how much they are violated. But with an experienced team I would never suggest the use of Black.

**Comment by lmz** [comment]
Alternatives: gray: https://github.com/dizballanze/gray
Also possibly relevant: https://marketplace.visualstudio.com/items?itemName=cpmcgrath.Codealignment

**Comment by e-lo** [comment]
@lmz - I did a tiny bit of rsch and think one of these options might be effective (note: have not tested yet)

1. Use [`black`s `#fmt:off` `#fmt:on`](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html) block wrapping commands. This would be the most complete and rigorous option and require minimal changes.
2. Use a combo of [`pycodestyle`](https://pycodestyle.pycqa.org/) (linter) and [`autopep8`](https://pypi.org/project/autopep8) (formatter) -- more on that below.

### `pycodestyle`/`autopep8`] Option

[`pycodestyle`](https://pycodestyle.pycqa.org/) is a linter, which you can configure to ignore [`E251: unexpected spaces around keyword / parameter equals`](https://pycodestyle.pycqa.org/en/latest/intro.html#error-codes). 

[`autopep8`](https://pypi.org/project/autopep8) is a formatter, which can be [configured]([`autopep8`](https://pypi.org/project/autopep8)) to follow your `pycodestyle` configuration - thus ignoring `E251` if desired. Note, you can also disable it line-by-line, but if you are doing that in the code, why not use Option 1/`black` ?

Caveats/Optionality
-  Note that the definition of `E251` is broader than what I think your desired use case is.

**Comment by lmz** [comment]
I didn't realize black is not completely uncompromising!  With the `#fmt:off`, `#fmt:on` option, plus apparently there's an option to allow the line lengths to be a bit longer, I can stop complaining.  Let's consider this issue cancelled.
